<#
.SYNOPSIS
  Demo 3 (part 2) - Creates a Function App (Flex Consumption, Node 22) and publishes the Quotes API.
.PARAMETER UploadFrontend
  Also uploads the front end (pointing to the public API) to the Demo 2 static website.
.EXAMPLE
  .\scripts\04-demo3-functions-deploy.ps1 -Initials yd
.EXAMPLE
  .\scripts\04-demo3-functions-deploy.ps1 -UploadFrontend
#>
param(
    [string]$Initials,
    [string]$Location,
    [switch]$UploadFrontend
)
. "$PSScriptRoot\common.ps1"

Assert-Command az   'Install the Azure CLI.'
Assert-Command func 'Install Azure Functions Core Tools v4.'
Assert-Command npm  'Install Node.js 22.'
Assert-AzLogin
$cfg = Get-DemoConfig -Initials $Initials -Location $Location
$apiFolder      = Join-Path $RepoRoot 'demos\demo3-functions\api'
$frontendFolder = Join-Path $RepoRoot 'demos\demo3-functions\frontend'

Initialize-ResourceGroup $cfg

Write-Step "Storage account for the Function App '$($cfg.FuncStorage)'"
Invoke-Az storage account create `
    --name $cfg.FuncStorage `
    --resource-group $cfg.ResourceGroup `
    --location $cfg.Location `
    --sku Standard_LRS `
    --allow-blob-public-access false `
    --output none
Write-Ok 'Storage account ready'

Write-Step "Function App '$($cfg.FunctionApp)' on Flex Consumption (Node 22)"
& az functionapp show --name $cfg.FunctionApp --resource-group $cfg.ResourceGroup --output none 2>$null
if ($LASTEXITCODE -ne 0) {
    Invoke-Az functionapp create `
        --name $cfg.FunctionApp `
        --resource-group $cfg.ResourceGroup `
        --storage-account $cfg.FuncStorage `
        --flexconsumption-location $cfg.Location `
        --runtime node `
        --runtime-version 22 `
        --output none
    Write-Ok 'Function App created'
} else {
    Write-Ok 'Function App already exists, reusing it'
}

Write-Step 'Allowing CORS (open to any origin: OK for class, NOT for production)'
& az functionapp cors add --name $cfg.FunctionApp --resource-group $cfg.ResourceGroup --allowed-origins '*' --output none 2>$null
if ($LASTEXITCODE -ne 0) { Write-Warning "Could not set CORS. Set it in Portal > Function App > API > CORS." }

Push-Location $apiFolder
try {
    Write-Step 'npm install'
    npm install --no-audit --no-fund
    if ($LASTEXITCODE -ne 0) { throw 'npm install failed' }

    Write-Step 'Publishing with func azure functionapp publish'
    func azure functionapp publish $cfg.FunctionApp
    if ($LASTEXITCODE -ne 0) { throw 'Publish failed. Wait a minute and run this script again.' }
} finally { Pop-Location }

$hostName = (Invoke-Az functionapp show --name $cfg.FunctionApp --resource-group $cfg.ResourceGroup --query defaultHostName --output tsv | Out-String).Trim()
$apiBase = "https://$hostName/api"

Write-Step 'Pointing the front end to the public API'
"// Generated by 04-demo3-functions-deploy.ps1`nwindow.API_BASE = '$apiBase';" |
    Set-Content -Path (Join-Path $frontendFolder 'config.js') -Encoding UTF8
Write-Ok "frontend/config.js -> $apiBase"

if ($UploadFrontend) {
    & az storage account show --name $cfg.StaticStorage --resource-group $cfg.ResourceGroup --output none 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Warning 'Static website from Demo 2 not found. Run 02-demo2-static-site.ps1 first.'
    } else {
        Write-Step 'Uploading the front end to the Demo 2 static website'
        $key = (Invoke-Az storage account keys list --account-name $cfg.StaticStorage --resource-group $cfg.ResourceGroup --query '[0].value' --output tsv | Out-String).Trim()
        Invoke-Az storage blob upload-batch --account-name $cfg.StaticStorage --account-key $key `
            --source $frontendFolder --destination '$web' --destination-path quotes --overwrite --output none
        $web = (Invoke-Az storage account show --name $cfg.StaticStorage --resource-group $cfg.ResourceGroup --query 'primaryEndpoints.web' --output tsv | Out-String).Trim()
        Write-Ok "Front end: $($web)quotes/index.html"
        Start-Process "$($web)quotes/index.html"
    }
}

Write-Host ""
Write-Host 'Demo 3 deployed:' -ForegroundColor Green
Write-Host "  GET  $apiBase/hello?name=UMG"
Write-Host "  GET  $apiBase/quotes"
Write-Host "  POST $apiBase/quotes"
Write-Host 'Test it: .\scripts\05-test-quotes-api.ps1' -ForegroundColor DarkGray
Write-Host 'Portal: Function App > Monitoring > Invocations / Log stream' -ForegroundColor DarkGray
Write-Host 'If you get 404 right after publishing, wait 1-2 minutes (the app is still loading).' -ForegroundColor DarkGray
